syntax = "proto3";

package webcast.shared.message;

import "webcast/model/message/common.proto";

message BaseProtoMessage {
  string method = 1;
  bytes payload = 2;
  int64 msg_id = 3;
  int32 msg_type = 4;
  int64 offset = 5;
  bool is_history = 6;
  int32 sample_flag = 7;
}

message CommonMessageData {
  string method = 1;
  int64 msg_id = 2;
  int64 room_id = 3;
  int64 create_time = 4;
  int32 monitor = 5;
  bool is_show_msg = 6;
  string describe = 7;
  model.message.common.Text display_text = 8;
  int64 fold_type = 9;
  int64 anchor_fold_type = 10;
  int64 priority_score = 11;
  string log_id = 12;
  string msg_process_filter_k = 13;
  string msg_process_filter_v = 14;
  string from_idc = 15;
  string to_idc = 16;
  repeated string filter_msg_tags = 17;
  LiveMessageSEI sei = 18;
  LiveMessageID depend_root_id = 19;
  LiveMessageID depend_id = 20;
  int64 anchor_priority_score = 21;
  int64 room_message_heat_level = 22;
  int64 fold_type_for_web = 23;
  int64 anchor_fold_type_for_web = 24;
  int64 client_send_time = 25;
  int32 dispatch_strategy = 26;
}

message LiveMessageID {
  string primary_id = 1;
  string message_scene = 2;
}

message LiveMessageSEI {
  LiveMessageID unique_id = 1;
  int64 timestamp = 2;
}

message ProtoMessageFetchResult {
  repeated BaseProtoMessage messages = 1;
  string cursor = 2;
  int64 fetch_interval = 3;
  int64 now = 4;
  string internal_ext = 5;
  int32 fetch_type = 6;
  map<string, string> route_params = 7;
  int64 heartbeat_duration = 8;
  bool need_ack = 9;
  string push_server = 10;
  bool is_first = 11;
  string history_comment_cursor = 12;
  bool history_no_more = 13;
}
