use std::env;
use std::error::Error;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

use prost::Message;
use prost_types::field_descriptor_proto::Type as ProtoFieldType;
use prost_types::{DescriptorProto, FieldDescriptorProto, FileDescriptorSet};

const SCHEMA_PATH: &str = "proto/tiktok_schema.proto";
const SCHEMA_INCLUDE_PATH: &str = "proto";
const DESCRIPTOR_FILE: &str = "tiktok_schema_descriptor.bin";
const MODULE_FILE: &str = "tiktok_schema.rs";
const REGISTRY_FILE: &str = "schema_registry.rs";
const PACKAGE_NAME: &str = "TikTok";
const ROOT_MESSAGES_NAME: &str = "Messages";

#[derive(Clone)]
struct MessageInfo {
    name: String,
    fields: Vec<FieldInfo>,
}

#[derive(Clone)]
struct FieldInfo {
    number: i32,
    name: String,
    kind: FieldKindInfo,
}

#[derive(Clone)]
enum FieldKindInfo {
    Varint,
    Fixed64,
    Fixed32,
    String,
    Bytes,
    Message(String),
}

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed={SCHEMA_PATH}");

    let output_dir = PathBuf::from(env::var("OUT_DIR")?);
    let descriptor_path = output_dir.join(DESCRIPTOR_FILE);
    let protoc = protoc_bin_vendored::protoc_bin_path()?;
    env::set_var("PROTOC", protoc);

    let mut config = prost_build::Config::new();
    config.include_file(MODULE_FILE);
    config.file_descriptor_set_path(&descriptor_path);
    config.compile_protos(&[SCHEMA_PATH], &[SCHEMA_INCLUDE_PATH])?;

    let descriptor_bytes = fs::read(descriptor_path)?;
    let descriptor_set = FileDescriptorSet::decode(descriptor_bytes.as_slice())?;
    let (messages, webcast_messages) = collect_schema_info(&descriptor_set)?;
    fs::write(
        output_dir.join(REGISTRY_FILE),
        render_registry(&messages, &webcast_messages),
    )?;
    Ok(())
}

fn collect_schema_info(
    descriptor_set: &FileDescriptorSet,
) -> Result<(Vec<MessageInfo>, Vec<String>), Box<dyn Error>> {
    let file = descriptor_set
        .file
        .iter()
        .find(|file| file.package.as_deref() == Some(PACKAGE_NAME))
        .ok_or("TikTok schema package is missing from the descriptor set")?;
    let root_messages = file
        .message_type
        .iter()
        .find(|message| message.name.as_deref() == Some(ROOT_MESSAGES_NAME))
        .ok_or("Messages root is missing from the TikTok schema")?;
    let webcast_messages = root_messages
        .nested_type
        .iter()
        .filter_map(|message| message.name.as_ref())
        .cloned()
        .collect();

    let mut messages = Vec::new();
    for message in &file.message_type {
        collect_messages(PACKAGE_NAME, message, &mut messages)?;
    }
    Ok((messages, webcast_messages))
}

fn collect_messages(
    parent_name: &str,
    message: &DescriptorProto,
    messages: &mut Vec<MessageInfo>,
) -> Result<(), Box<dyn Error>> {
    let short_name = message
        .name
        .as_deref()
        .ok_or("schema message has no name")?;
    let name = format!("{parent_name}.{short_name}");
    let fields = message
        .field
        .iter()
        .filter_map(field_info)
        .collect::<Vec<_>>();
    messages.push(MessageInfo {
        name: name.clone(),
        fields,
    });
    for nested in &message.nested_type {
        collect_messages(&name, nested, messages)?;
    }
    Ok(())
}

fn field_info(field: &FieldDescriptorProto) -> Option<FieldInfo> {
    let number = field.number?;
    if number <= 0 {
        return None;
    }
    let name = field.name.clone()?;
    let kind = match ProtoFieldType::try_from(field.r#type?).ok()? {
        ProtoFieldType::Double | ProtoFieldType::Fixed64 | ProtoFieldType::Sfixed64 => {
            FieldKindInfo::Fixed64
        }
        ProtoFieldType::Float | ProtoFieldType::Fixed32 | ProtoFieldType::Sfixed32 => {
            FieldKindInfo::Fixed32
        }
        ProtoFieldType::String => FieldKindInfo::String,
        ProtoFieldType::Bytes => FieldKindInfo::Bytes,
        ProtoFieldType::Message | ProtoFieldType::Group => FieldKindInfo::Message(
            field
                .type_name
                .as_deref()
                .unwrap_or_default()
                .trim_start_matches('.')
                .to_owned(),
        ),
        ProtoFieldType::Int64
        | ProtoFieldType::Uint64
        | ProtoFieldType::Int32
        | ProtoFieldType::Bool
        | ProtoFieldType::Uint32
        | ProtoFieldType::Enum
        | ProtoFieldType::Sint32
        | ProtoFieldType::Sint64 => FieldKindInfo::Varint,
    };
    Some(FieldInfo { number, name, kind })
}

fn render_registry(messages: &[MessageInfo], webcast_messages: &[String]) -> String {
    let mut source = String::new();
    source.push_str("// @generated by build.rs from proto/tiktok_schema.proto.\n");
    source.push_str("// Do not edit manually.\n\n");
    let _ = writeln!(
        source,
        "/// Number of message schemas in the bundled snapshot.\npub const GENERATED_SCHEMA_MESSAGE_COUNT: usize = {};\n",
        messages.len()
    );
    let _ = writeln!(
        source,
        "/// Number of page WebSocket methods mapped from the `Messages` namespace.\npub const GENERATED_WEBCAST_METHOD_COUNT: usize = {};\n",
        webcast_messages.len()
    );

    for (index, message) in messages.iter().enumerate() {
        let _ = writeln!(source, "static FIELDS_{index}: &[FieldSchema] = &[");
        for field in &message.fields {
            let kind = render_field_kind(&field.kind);
            let _ = writeln!(
                source,
                "    FieldSchema {{ number: {}, name: {:?}, kind: {kind} }},",
                field.number, field.name
            );
        }
        source.push_str("];\n\n");
    }

    source.push_str("static SCHEMAS: &[MessageSchema] = &[\n");
    for (index, message) in messages.iter().enumerate() {
        let _ = writeln!(
            source,
            "    MessageSchema {{ name: {:?}, fields: FIELDS_{index} }},",
            message.name
        );
    }
    source.push_str("];\n\n");
    source.push_str("/// Find a bundled schema by its fully qualified protobuf name.\n");
    source.push_str("pub fn schema_by_name(name: &str) -> Option<&'static MessageSchema> {\n");
    source.push_str("    SCHEMAS.iter().find(|schema| schema.name == name)\n");
    source.push_str("}\n\n");
    source.push_str("/// Find the schema associated with a TikTok WebSocket method.\n");
    source.push_str("///\n");
    source.push_str(
        "/// `TikTok.Messages` holds most page messages, but the snapshot also declares\n",
    );
    source
        .push_str("/// message types under sibling namespaces such as `TikTok.UnknownObjects`.\n");
    source.push_str(
        "/// Searching only `Messages` reported those as unknown even though a descriptor\n",
    );
    source.push_str(
        "/// existed, so `Messages` is preferred and the other namespaces are a fallback.\n",
    );
    source.push_str("pub fn schema_for_method(method: &str) -> Option<&'static MessageSchema> {\n");
    source.push_str("    let short_name = method.strip_prefix(\"Webcast\")?;\n");
    source.push_str("    if let Some(schema) = SCHEMAS.iter().find(|schema| {\n");
    source.push_str("        schema.name.strip_prefix(\"TikTok.Messages.\") == Some(short_name)\n");
    source.push_str("    }) {\n");
    source.push_str("        return Some(schema);\n");
    source.push_str("    }\n");
    source
        .push_str("    // Only top-level `TikTok.<namespace>.<Name>` types, never a nested type\n");
    source.push_str("    // that happens to share the name.\n");
    source.push_str("    SCHEMAS.iter().find(|schema| {\n");
    source.push_str("        let mut segments = schema.name.split('.');\n");
    source.push_str("        segments.next() == Some(\"TikTok\")\n");
    source.push_str("            && segments.next().is_some()\n");
    source.push_str("            && segments.next() == Some(short_name)\n");
    source.push_str("            && segments.next().is_none()\n");
    source.push_str("    })\n");
    source.push_str("}\n");
    source
}

fn render_field_kind(kind: &FieldKindInfo) -> String {
    match kind {
        FieldKindInfo::Varint => "FieldKind::Varint".into(),
        FieldKindInfo::Fixed64 => "FieldKind::Fixed64".into(),
        FieldKindInfo::Fixed32 => "FieldKind::Fixed32".into(),
        FieldKindInfo::String => "FieldKind::String".into(),
        FieldKindInfo::Bytes => "FieldKind::Bytes".into(),
        FieldKindInfo::Message(name) => format!("FieldKind::Message({name:?})"),
    }
}
