// GENERATED by scripts/headless/tools/gen-canvas.mjs — do not edit by hand.
//
// The canvas fingerprint the shim reports, as data rather than as code. The SDK folds
// `toDataURL` into the signature: it reaches `X-Gnarly` from byte 2 and moves 249 of its 332
// bytes (`scripts/headless/byte-map.mjs`), which makes its content the largest single
// contribution after the clock.
//
// It is a real 300×150 RGBA PNG. An earlier version returned a 20-byte string — a PNG signature
// followed by a truncated IHDR, undecodable as an image and impossible for any real canvas to
// produce. Building the valid one needs DEFLATE, so it is built at generation time and kept here
// as a constant: the shim then needs no compressor, no `Buffer`, and no Node, which is what lets
// the signer run in an embedded engine.
//
// Nothing here is random. Two runs must agree, or every differential in this directory breaks.

export const CANVAS_WIDTH = 300;
export const CANVAS_HEIGHT = 150;

/// The pixel at (x, y). `getImageData` reports these, and the PNG above is exactly these pixels.
export function inkAt(x, y) {
  return (x * 7 + y * 13) % 97 < 11;
}

/// Text metrics that depend on the text, the way a real font engine's do. A constant width is
/// another way of reporting "no canvas".
export function measureTextWidth(text) {
  let width = 0;
  for (const character of String(text)) width += ((character.codePointAt(0) % 7) + 4) * 0.5;
  return width;
}

export const CANVAS_DATA_URL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAEVklEQVR42u3csY0cQRAEwbTljaNxNPGUJ+gBXyFQPSGs2MJOINXq69fv77/f5/P50bd099Ob/33HgAGDf/u3wIqLAYMVg8CKiwGDFYPAiosBgxWDwIqLAYMVg8CKiwGDlbvAiosBg5W3DKy4GDBYMQisuBgwWDEIrLgYMFgxCKy4GDBYMQisuBgwWDEIrLgYMFgxCKy4GDBYuQusuBgwWHnLwIqLAYMVg8CKiwGDFYPAiosBgxWDwIqLAYMVg8CKiwGDFYPAiosBgxWDwIqLAQPzMmDFxYDBq/MyYBkwYBBYcTFgsGIQWHExYLBiEFhxMWCwYhBYcTFgsGIQWHExYLBiEFhxMWBgXgasuBgweHFeBiwDBgzOzsuAZcDgpkFgxcWAwYpBYMXFgMGKQWDFxYDBikFgxcWAwYpBYMXFgIF5GbDiYsDgtXkZsAwYMDg7LwOWAYO7BoEVFwMGKwaBFRcDBisGgRUXAwYrBoEVFwMGKwaBFRcDBuZlwIqLAYOX5mXAMmDA4Oy8DFgGDG4bBFZcDBisGARWXAwYrBgEVlwMGKwYBFZcDBisGARWXAwYmJcBKy4GDF6ZlwHLgAGDs/MyYBkwuG8QWHExYLBiEFhxMWCwYhBYcTFgsGIQWHExYLBiEFhxMWBgXgasuBgweGFeBiwDBgzOzsuAZcDgDYPAiosBgxWDwIqLAYMVg8CKiwGDFYPAiosBgxWDwIqLAQPzMmDFxYDB9XkZsAwYMDg7LwOWAYN3DAIrLgYMVgwCKy4GDFYMAisuBgxWDAIrLgYMVgwCKy4GDMzLgBUXAwaX52XAMmDA4Oy8DFgGDN4yCKy4GDBYMQisuBgwWDEIrLgYMFgxCKy4GDBYMQisuBgweH5eBqy4GDA4Oy8DlgEDBmfnZcAyYPCeQWDFxYDBikFgxcWAwYpBYMXFgMGKQWDFxYDBikFgxcWAwdPzMmDFxYDB2XkZsAwYMDg7LwOWAYM3DQIrLgYMVgwCKy4GDFYMAisuBgxWDAIrLgYMVgwCKy4GDFYMAisuBgzMy4AVFwMGr8/LgGXA4F2DwIqLAYMVg8CKiwGDFYPAiosBgxWDwIqLAYMVg8CKiwGDFYPAiosBA/MyYMXFgMHL8zJgGTB42yCw4mLAYMUgsOJiwGDFILDiYsBgxSCw4mLAYMUgsOJiwGDFILDiYsDAvAxYcTFg8Oq8DFgGDBgEVlwMGKwYBFZcDBisGARWXAwYrBgEVlwMGKwYBFZcDBisGARWXAwYmJcBKy4GDF6clwHLgAGDs/MyYBkwuGkQWHExYLBiEFhxMWCwYhBYcTFgsGIQWHExYLBiEFhxMWBgXgasuBgweG1eBiwDBgzOzsuAZcDgrkFgxcWAwYpBYMXFgMGKQWDFxYDBikFgxcWAwYpBYMXFgIF5GbDiYsDgpXkZsAwYMDg7LwOWAYPbBoEVFwMGKwaBFRcDBisGgRUXAwYrBoEVFwMGKwZ/APu9q34QM3OPAAAAAElFTkSuQmCC';
