//! The QuickJS engine: small, interpreted, no JIT.
//!
//! Chosen first because it passes the parity test in 1.9 MB. It is roughly nine times slower per
//! signature than V8, which is the whole trade — see `docs/13-embedded-runtime.md`.

use rand::RngCore;
use rquickjs::{Context, Function, Runtime};

use crate::{Engine, EmbeddedError, BOOTSTRAP};

/// A prepared QuickJS context. Lives on the signer's thread; never crosses one.
pub struct QuickJs {
    context: Context,
    // The runtime owns the heap the context lives in, so it must outlive it.
    _runtime: Runtime,
}

impl Engine for QuickJs {
    const NAME: &'static str = "QuickJS";

    fn start(bundle: &str, options: &str) -> Result<Self, EmbeddedError> {
        let runtime = Runtime::new().map_err(|error| EmbeddedError::Engine(error.to_string()))?;
        let context =
            Context::full(&runtime).map_err(|error| EmbeddedError::Engine(error.to_string()))?;

        context.with(|ctx| -> Result<(), EmbeddedError> {
            // The engine has no `crypto`, and the SDK's entropy is not decoration: signatures built
            // from a counter come out short, which was measured. The bootstrap wires its random
            // source to this function when it finds no `crypto`, so it must exist before the script
            // runs.
            let random = Function::new(ctx.clone(), |count: usize| {
                let mut bytes = vec![0u8; count.min(crate::MAX_RANDOM_BYTES)];
                rand::thread_rng().fill_bytes(&mut bytes);
                bytes
            })
            .map_err(|error| EmbeddedError::Engine(error.to_string()))?;
            ctx.globals()
                .set("__ttl_random_bytes", random)
                .map_err(|error| EmbeddedError::Engine(error.to_string()))?;

            ctx.eval::<(), _>(BOOTSTRAP)
                .map_err(|error| EmbeddedError::Engine(describe(&ctx, error)))?;

            let prepare: Function = ctx
                .globals()
                .get("ttlPrepare")
                .map_err(|error| EmbeddedError::Engine(describe(&ctx, error)))?;
            let out: String = prepare
                .call((bundle, options))
                .map_err(|error| EmbeddedError::Bundle(describe(&ctx, error)))?;
            crate::read_error(&out).map_err(EmbeddedError::Bundle)
        })?;

        Ok(Self {
            context,
            _runtime: runtime,
        })
    }

    fn sign(&mut self, url: &str, product: &str) -> Result<String, String> {
        self.context.with(|ctx| {
            let sign: Function = ctx
                .globals()
                .get("ttlSignUrl")
                .map_err(|error| describe(&ctx, error))?;
            let out: String = sign
                .call((url, product))
                .map_err(|error| describe(&ctx, error))?;
            crate::read(&out)
        })
    }
}

/// QuickJS reports "Exception generated by QuickJS" and leaves the real error on the context.
fn describe(ctx: &rquickjs::Ctx, error: rquickjs::Error) -> String {
    if !matches!(error, rquickjs::Error::Exception) {
        return error.to_string();
    }
    let value = ctx.catch();
    match value.as_exception() {
        Some(exception) => exception.message().unwrap_or_else(|| "unknown error".into()),
        None => "unknown error".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The random source is injected from Rust and wired up by the bootstrap. If that wiring
    /// breaks, the SDK swallows the exception inside its own interpreter and quietly omits parts of
    /// its API — which is a far harder failure to read than an error here.
    #[test]
    fn the_injected_random_source_reaches_the_sandbox() {
        let runtime = Runtime::new().expect("runtime");
        let context = Context::full(&runtime).expect("context");
        context.with(|ctx| {
            let random = Function::new(ctx.clone(), |count: usize| {
                let mut bytes = vec![0u8; count.min(crate::MAX_RANDOM_BYTES)];
                rand::thread_rng().fill_bytes(&mut bytes);
                bytes
            })
            .expect("random function");
            ctx.globals()
                .set("__ttl_random_bytes", random)
                .expect("install");
            ctx.eval::<(), _>(BOOTSTRAP).expect("bootstrap");

            let kind: String = ctx
                .eval("typeof globalThis.TTL_RANDOM_SOURCE")
                .expect("read the source");
            assert_eq!(
                kind, "function",
                "the bootstrap did not wire the random source"
            );

            let filled: String = ctx
                .eval(
                    "(function () { const a = new Uint8Array(8); \
                     globalThis.TTL_RANDOM_SOURCE(a); \
                     return Array.from(a).join(','); })()",
                )
                .expect("fill an array");
            assert_eq!(filled.split(',').count(), 8, "got: {filled}");
            assert!(
                filled.split(',').any(|byte| byte != "0"),
                "every byte was zero: {filled}"
            );
        });
    }
}
