// Regenerate the canvas fingerprint the shim reports.
//
//   node scripts/headless/tools/gen-canvas.mjs
//
// ## Why this is generated rather than built at runtime
//
// The fingerprint is a real 300×150 RGBA PNG, and building one needs DEFLATE. In Node that is one
// call to `zlib.deflateSync`; in an embedded engine — QuickJS, Boa, a browser — it is a compressor
// nobody wants to ship inside a sandbox. The image never changes: the pixels come from `inkAt`,
// which is a pure function of the coordinates, so the same bytes come out every time.
//
// So it is computed once, here, and written into `../lib/canvas.mjs` as a constant. The shim then
// depends on no compression, no `Buffer`, and no Node at all — which is what makes the signer
// portable to an engine that has none of them.
//
// Both halves are emitted by this one script on purpose. `getImageData` reports pixels through
// `inkAt`, and the PNG *is* those pixels; if the two were maintained separately they could disagree,
// and a canvas whose image does not match its own pixel data is a fingerprint no browser produces.

import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const TARGET = path.join(HERE, '..', 'lib', 'canvas.mjs');

const CANVAS_WIDTH = 300;
const CANVAS_HEIGHT = 150;

/// The pixel a fingerprint canvas has at (x, y). Structured rather than uniform, so the image
/// carries detail the way drawn text does. Emitted into the generated file verbatim.
const INK_AT = `function inkAt(x, y) {
  return (x * 7 + y * 13) % 97 < 11;
}`;
// eslint-disable-next-line no-new-func -- the generated source and the generator must agree.
const inkAt = new Function(`${INK_AT}; return inkAt;`)();

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buffer) {
  let c = 0xFFFFFFFF;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 255] ^ (c >>> 8);
  return (c ^ 0xFFFFFFFF) >>> 0;
}

function pngChunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const tag = Buffer.from(type, 'ascii');
  const checksum = Buffer.alloc(4);
  checksum.writeUInt32BE(crc32(Buffer.concat([tag, data])));
  return Buffer.concat([length, tag, data, checksum]);
}

function fingerprintDataUrl() {
  const stride = CANVAS_WIDTH * 4 + 1;
  const raw = Buffer.alloc(stride * CANVAS_HEIGHT);
  for (let y = 0; y < CANVAS_HEIGHT; y += 1) {
    const row = y * stride;
    raw[row] = 0; // filter: none
    for (let x = 0; x < CANVAS_WIDTH; x += 1) {
      const at = row + 1 + x * 4;
      const ink = inkAt(x, y);
      raw[at] = ink ? 34 : 250;
      raw[at + 1] = ink ? 102 : 250;
      raw[at + 2] = ink ? 170 : 250;
      raw[at + 3] = 255;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(CANVAS_WIDTH, 0);
  ihdr.writeUInt32BE(CANVAS_HEIGHT, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: RGBA
  const png = Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
  return `data:image/png;base64,${png.toString('base64')}`;
}

const dataUrl = fingerprintDataUrl();

const generated = `// GENERATED by scripts/headless/tools/gen-canvas.mjs — do not edit by hand.
//
// The canvas fingerprint the shim reports, as data rather than as code. The SDK folds
// \`toDataURL\` into the signature: it reaches \`X-Gnarly\` from byte 2 and moves 249 of its 332
// bytes (\`scripts/headless/byte-map.mjs\`), which makes its content the largest single
// contribution after the clock.
//
// It is a real 300×150 RGBA PNG. An earlier version returned a 20-byte string — a PNG signature
// followed by a truncated IHDR, undecodable as an image and impossible for any real canvas to
// produce. Building the valid one needs DEFLATE, so it is built at generation time and kept here
// as a constant: the shim then needs no compressor, no \`Buffer\`, and no Node, which is what lets
// the signer run in an embedded engine.
//
// Nothing here is random. Two runs must agree, or every differential in this directory breaks.

export const CANVAS_WIDTH = ${CANVAS_WIDTH};
export const CANVAS_HEIGHT = ${CANVAS_HEIGHT};

/// The pixel at (x, y). \`getImageData\` reports these, and the PNG above is exactly these pixels.
export ${INK_AT}

/// Text metrics that depend on the text, the way a real font engine's do. A constant width is
/// another way of reporting "no canvas".
export function measureTextWidth(text) {
  let width = 0;
  for (const character of String(text)) width += ((character.codePointAt(0) % 7) + 4) * 0.5;
  return width;
}

export const CANVAS_DATA_URL = '${dataUrl}';
`;

fs.writeFileSync(TARGET, generated);
console.log(`wrote ${path.relative(path.join(HERE, '..', '..', '..'), TARGET)}`);
console.log(`  ${CANVAS_WIDTH}×${CANVAS_HEIGHT} PNG, ${dataUrl.length} bytes of data URL`);
