syntax = "proto3";

package webcast.im;

enum MemberMessageAction {
  MEMBER_MESSAGE_ACTION_UNKNOWN = 0;
  MEMBER_MESSAGE_ACTION_JOINED = 1;
  MEMBER_MESSAGE_ACTION_SUBSCRIBED = 3;
}

enum CommentTag {
  COMMENT_TAG_NORMAL = 0;
  COMMENT_TAG_CANDIDATE = 1;
  COMMENT_TAG_OVERAGE = 2;
}

enum MuteStatus {
  MUTE_STATUS_MUTE = 0;
  MUTE_STATUS_UN_MUTE = 1;
}

enum ControlAction {
  CONTROL_ACTION_FALLBACK_UNKNOWN = 0;
  CONTROL_ACTION_STREAM_PAUSED = 1;
  CONTROL_ACTION_STREAM_UNPAUSED = 2;
  CONTROL_ACTION_STREAM_ENDED = 3;
  CONTROL_ACTION_STREAM_SUSPENDED = 4;
}
