//! The QuickJS engine: small, interpreted, no JIT — and the only engine here.
//!
//! Adapted from `ttl-sign-embedded/src/quickjs.rs`, minus the `Engine` trait (there is no
//! second engine on mobile: V8/`deno_core` does not cross-compile to Android sanely) and
//! minus `tokio` (JNI calls block). Behaviour is identical: same bootstrap, same random
//! source injection, same driver calls — which is what makes the pinned vectors in
//! `tests/mobile_sign.rs` comparable with the server's.

use rand::RngCore;
use rquickjs::{Context, Function, Runtime};

use crate::{MobileError, BOOTSTRAP, MAX_RANDOM_BYTES};

/// A prepared QuickJS context. Lives on the signer's thread; never crosses one.
pub struct QuickJs {
    context: Context,
    // The runtime owns the heap the context lives in, so it must outlive it.
    _runtime: Runtime,
}

impl QuickJs {
    pub fn start(bundle: &str, options: &str) -> Result<Self, MobileError> {
        let runtime = Runtime::new().map_err(|e| MobileError::Engine(e.to_string()))?;
        let context = Context::full(&runtime).map_err(|e| MobileError::Engine(e.to_string()))?;

        context.with(|ctx| -> Result<(), MobileError> {
            // The engine has no `crypto`, so the host installs `__ttl_random_bytes(n)`
            // before the bootstrap runs and the sandbox wires its random source to it.
            let random = Function::new(ctx.clone(), |count: usize| {
                let mut bytes = vec![0u8; count.min(MAX_RANDOM_BYTES)];
                rand::thread_rng().fill_bytes(&mut bytes);
                bytes
            })
            .map_err(|e| MobileError::Engine(e.to_string()))?;
            ctx.globals()
                .set("__ttl_random_bytes", random)
                .map_err(|e| MobileError::Engine(e.to_string()))?;

            ctx.eval::<(), _>(BOOTSTRAP)
                .map_err(|e| MobileError::Engine(describe(&ctx, e)))?;

            let prepare: Function = ctx
                .globals()
                .get("ttlPrepare")
                .map_err(|e| MobileError::Engine(describe(&ctx, e)))?;
            let out: String = prepare
                .call((bundle, options))
                .map_err(|e| MobileError::Bundle(describe(&ctx, e)))?;
            crate::read_error(&out)
        })?;

        Ok(Self {
            context,
            _runtime: runtime,
        })
    }

    pub fn sign(&mut self, url: &str, product: &str) -> Result<String, MobileError> {
        self.context.with(|ctx| {
            let sign: Function = ctx
                .globals()
                .get("ttlSignUrl")
                .map_err(|e| MobileError::Sign(describe(&ctx, e)))?;
            let out: String = sign
                .call((url, product))
                .map_err(|e| MobileError::Sign(describe(&ctx, e)))?;
            crate::read_signed(&out)
        })
    }
}

/// QuickJS reports "Exception generated by QuickJS" and leaves the real error on the context.
fn describe(ctx: &rquickjs::Ctx, error: rquickjs::Error) -> String {
    if !matches!(error, rquickjs::Error::Exception) {
        return error.to_string();
    }
    let value = ctx.catch();
    match value.as_exception() {
        Some(exception) => exception
            .message()
            .unwrap_or_else(|| "unknown error".into()),
        None => "unknown error".into(),
    }
}
